[2023-01-24 09:18:38,931] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2023-01-24 09:18:38,945] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2023-01-24 09:18:38,945] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 09:18:38,945] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-01-24 09:18:38,945] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 09:18:38,959] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-02 06:00:00+00:00
[2023-01-24 09:18:38,967] {standard_task_runner.py:52} INFO - Started process 1647 to run task
[2023-01-24 09:18:38,972] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpabaqfd9g', '--error-file', '/tmp/tmp70o5arai']
[2023-01-24 09:18:38,973] {standard_task_runner.py:77} INFO - Job 102: Subtask ingest
[2023-01-24 09:18:39,054] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host 7e31e7c7b196
[2023-01-24 09:18:39,118] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-24 09:18:39,144] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2023-01-24 09:18:39,146] {logging_mixin.py:109} INFO - yellow_taxi_2021_05 /opt/***/yellow_tripdata_2021-05.csv
[2023-01-24 09:18:39,157] {logging_mixin.py:109} INFO - Connection established...
[2023-01-24 09:18:39,469] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 23, in ingest_callable
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'lpep_pickup_datetime'
[2023-01-24 09:18:39,489] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210502T060000, start_date=20230124T091838, end_date=20230124T091839
[2023-01-24 09:18:39,505] {standard_task_runner.py:92} ERROR - Failed to execute job 102 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 23, in ingest_callable
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'lpep_pickup_datetime'
[2023-01-24 09:18:39,548] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-24 09:18:39,598] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
