[2023-01-29 12:46:47,168] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:47,178] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:47,178] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:47,179] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:46:47,180] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:47,190] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-11-01 00:00:00+00:00
[2023-01-29 12:46:47,195] {standard_task_runner.py:52} INFO - Started process 7721 to run task
[2023-01-29 12:46:47,198] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '424', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpe4im3vc5', '--error-file', '/tmp/tmpsylcplsc']
[2023-01-29 12:46:47,199] {standard_task_runner.py:77} INFO - Job 424: Subtask cast_parquet_columns_task
[2023-01-29 12:46:47,259] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-11-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:46:47,303] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:46:47,324] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T00:00:00+00:00
[2023-01-29 12:46:47,326] {logging_mixin.py:109} INFO - /opt/***
[2023-01-29 12:46:47,525] {logging_mixin.py:109} WARNING - --- Logging error ---
[2023-01-29 12:46:47,531] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2023-01-29 12:46:47,532] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2023-01-29 12:46:47,533] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2023-01-29 12:46:47,533] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2023-01-29 12:46:47,534] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2023-01-29 12:46:47,535] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2023-01-29 12:46:47,535] {logging_mixin.py:109} WARNING - Call stack:
[2023-01-29 12:46:47,551] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-01-29 12:46:47,552] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 48, in main
    args.func(args)
[2023-01-29 12:46:47,552] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:46:47,553] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:46:47,554] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/scheduler_command.py", line 75, in scheduler
    _run_scheduler_job(args=args)
[2023-01-29 12:46:47,555] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job
    job.run()
[2023-01-29 12:46:47,555] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2023-01-29 12:46:47,556] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/scheduler_job.py", line 620, in _execute
    self.executor.start()
[2023-01-29 12:46:47,557] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 356, in start
    self.impl.start()
[2023-01-29 12:46:47,557] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 298, in start
    worker.start()
[2023-01-29 12:46:47,558] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
[2023-01-29 12:46:47,559] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2023-01-29 12:46:47,559] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
[2023-01-29 12:46:47,560] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
[2023-01-29 12:46:47,561] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
[2023-01-29 12:46:47,561] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
[2023-01-29 12:46:47,562] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 67, in run
    return super().run()
[2023-01-29 12:46:47,563] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
[2023-01-29 12:46:47,563] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 190, in do_work
    self.execute_work(key=key, command=command)
[2023-01-29 12:46:47,564] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 84, in execute_work
    state = self._execute_work_in_fork(command)
[2023-01-29 12:46:47,565] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 124, in _execute_work_in_fork
    args.func(args)
[2023-01-29 12:46:47,565] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:46:47,566] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:46:47,567] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-01-29 12:46:47,567] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2023-01-29 12:46:47,568] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2023-01-29 12:46:47,569] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2023-01-29 12:46:47,570] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2023-01-29 12:46:47,570] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2023-01-29 12:46:47,571] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2023-01-29 12:46:47,571] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:46:47,572] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:46:47,573] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-01-29 12:46:47,573] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2023-01-29 12:46:47,574] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2023-01-29 12:46:47,575] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2023-01-29 12:46:47,575] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2023-01-29 12:46:47,576] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2023-01-29 12:46:47,577] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2023-01-29 12:46:47,577] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2023-01-29 12:46:47,578] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-01-29 12:46:47,579] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/data_ingestion_gcs_dag.py", line 65, in cast_parquet_columns
    logging.info('table', table)
[2023-01-29 12:46:47,579] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2023-01-29 12:46:47,580] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2023-01-29 12:46:47,580] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2023-01-29 12:46:47,581] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2023-01-29 12:46:47,582] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2023-01-29 12:46:47,583] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2023-01-29 12:46:47,584] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 67, in emit
    self.handler.emit(record)
[2023-01-29 12:46:47,585] {logging_mixin.py:109} WARNING - Message: 'table'
Arguments: (pyarrow.Table
dispatching_base_num: string
pickup_datetime: timestamp[s]
dropOff_datetime: timestamp[s]
PUlocationID: int64
DOlocationID: int64
SR_Flag: int64
Affiliated_base_number: string,)
[2023-01-29 12:46:47,919] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:46:47,950] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20191101T000000, start_date=20230129T124647, end_date=20230129T124647
[2023-01-29 12:46:48,058] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:46:48,096] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
