[2023-01-29 12:37:36,138] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 12:37:36,147] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 12:37:36,148] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:37:36,149] {taskinstance.py:1239} INFO - Starting attempt 9 of 10
[2023-01-29 12:37:36,150] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:37:36,160] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-02-01 00:00:00+00:00
[2023-01-29 12:37:36,165] {standard_task_runner.py:52} INFO - Started process 5865 to run task
[2023-01-29 12:37:36,169] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2c9cj_kb', '--error-file', '/tmp/tmpl92k52il']
[2023-01-29 12:37:36,170] {standard_task_runner.py:77} INFO - Job 375: Subtask cast_parquet_columns_task
[2023-01-29 12:37:36,225] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:37:36,266] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:37:36,290] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2023-01-29 12:37:36,292] {logging_mixin.py:109} INFO - /opt/***
[2023-01-29 12:37:36,483] {logging_mixin.py:109} WARNING - --- Logging error ---
[2023-01-29 12:37:36,485] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2023-01-29 12:37:36,486] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2023-01-29 12:37:36,487] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2023-01-29 12:37:36,488] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2023-01-29 12:37:36,489] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2023-01-29 12:37:36,490] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2023-01-29 12:37:36,491] {logging_mixin.py:109} WARNING - Call stack:
[2023-01-29 12:37:36,495] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-01-29 12:37:36,496] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 48, in main
    args.func(args)
[2023-01-29 12:37:36,497] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:37:36,498] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:37:36,498] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/scheduler_command.py", line 75, in scheduler
    _run_scheduler_job(args=args)
[2023-01-29 12:37:36,500] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job
    job.run()
[2023-01-29 12:37:36,500] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2023-01-29 12:37:36,501] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/scheduler_job.py", line 620, in _execute
    self.executor.start()
[2023-01-29 12:37:36,502] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 356, in start
    self.impl.start()
[2023-01-29 12:37:36,503] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 298, in start
    worker.start()
[2023-01-29 12:37:36,504] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
[2023-01-29 12:37:36,504] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2023-01-29 12:37:36,505] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
[2023-01-29 12:37:36,506] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
[2023-01-29 12:37:36,507] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
[2023-01-29 12:37:36,508] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
[2023-01-29 12:37:36,508] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 67, in run
    return super().run()
[2023-01-29 12:37:36,509] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
[2023-01-29 12:37:36,510] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 190, in do_work
    self.execute_work(key=key, command=command)
[2023-01-29 12:37:36,510] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 84, in execute_work
    state = self._execute_work_in_fork(command)
[2023-01-29 12:37:36,511] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/local_executor.py", line 124, in _execute_work_in_fork
    args.func(args)
[2023-01-29 12:37:36,512] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:37:36,512] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:37:36,513] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-01-29 12:37:36,514] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2023-01-29 12:37:36,514] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2023-01-29 12:37:36,515] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2023-01-29 12:37:36,516] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2023-01-29 12:37:36,517] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2023-01-29 12:37:36,517] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2023-01-29 12:37:36,518] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2023-01-29 12:37:36,519] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2023-01-29 12:37:36,519] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-01-29 12:37:36,520] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2023-01-29 12:37:36,521] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2023-01-29 12:37:36,521] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2023-01-29 12:37:36,522] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2023-01-29 12:37:36,523] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2023-01-29 12:37:36,524] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2023-01-29 12:37:36,524] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2023-01-29 12:37:36,525] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-01-29 12:37:36,526] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/data_ingestion_gcs_dag.py", line 65, in cast_parquet_columns
    logging.info('table', table)
[2023-01-29 12:37:36,526] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2023-01-29 12:37:36,527] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2023-01-29 12:37:36,528] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2023-01-29 12:37:36,528] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2023-01-29 12:37:36,529] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2023-01-29 12:37:36,530] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2023-01-29 12:37:36,531] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 67, in emit
    self.handler.emit(record)
[2023-01-29 12:37:36,532] {logging_mixin.py:109} WARNING - Message: 'table'
Arguments: (pyarrow.Table
dispatching_base_num: string
pickup_datetime: timestamp[s]
dropOff_datetime: timestamp[s]
PUlocationID: int64
DOlocationID: int64
SR_Flag: int64
Affiliated_base_number: string,)
[2023-01-29 12:37:36,879] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:37:36,904] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190201T000000, start_date=20230129T123736, end_date=20230129T123736
[2023-01-29 12:37:37,080] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:37:37,118] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
