[2023-01-24 05:07:59,482] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.parquet_to_csv scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2023-01-24 05:07:59,494] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.parquet_to_csv scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2023-01-24 05:07:59,494] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 05:07:59,494] {taskinstance.py:1239} INFO - Starting attempt 7 of 7
[2023-01-24 05:07:59,494] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 05:07:59,509] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): parquet_to_csv> on 2021-04-02 06:00:00+00:00
[2023-01-24 05:07:59,516] {standard_task_runner.py:52} INFO - Started process 15510 to run task
[2023-01-24 05:07:59,523] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'parquet_to_csv', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpn058iydu', '--error-file', '/tmp/tmpdrk54kwh']
[2023-01-24 05:07:59,525] {standard_task_runner.py:77} INFO - Job 82: Subtask parquet_to_csv
[2023-01-24 05:07:59,604] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.parquet_to_csv scheduled__2021-04-02T06:00:00+00:00 [running]> on host 6018d13d82e3
[2023-01-24 05:07:59,665] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-24 05:07:59,691] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=parquet_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2023-01-24 05:07:59,711] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_local.py", line 20, in parquet_to_csv
    df = pd.read_parquet(parquet_file, engine = 'pyarrow')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_"2021-04".parquet'
[2023-01-24 05:07:59,727] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=parquet_to_csv, execution_date=20210402T060000, start_date=20230124T050759, end_date=20230124T050759
[2023-01-24 05:07:59,743] {standard_task_runner.py:92} ERROR - Failed to execute job 82 for task parquet_to_csv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_local.py", line 20, in parquet_to_csv
    df = pd.read_parquet(parquet_file, engine = 'pyarrow')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/yellow_tripdata_"2021-04".parquet'
[2023-01-24 05:07:59,776] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-24 05:07:59,828] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
