[2023-01-29 06:22:12,189] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 06:22:12,205] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 06:22:12,207] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 06:22:12,208] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-01-29 06:22:12,209] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 06:22:12,227] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_fhv_partitioned_clustered_table_task> on 2019-02-01 00:00:00+00:00
[2023-01-29 06:22:12,235] {standard_task_runner.py:52} INFO - Started process 41665 to run task
[2023-01-29 06:22:12,241] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'bq_create_fhv_partitioned_clustered_table_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpa5vrt7xx', '--error-file', '/tmp/tmpg75q_ai5']
[2023-01-29 06:22:12,243] {standard_task_runner.py:77} INFO - Job 251: Subtask bq_create_fhv_partitioned_clustered_table_task
[2023-01-29 06:22:12,326] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-29 06:22:12,389] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=bq_create_fhv_partitioned_clustered_table_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2023-01-29 06:22:12,391] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-01-29 06:22:12,401] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 06:22:12,412] {bigquery.py:1637} INFO - Inserting job ***_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_02_01T00_00_00_00_00_12cc801470e3cb15c8ca42b84054d278
[2023-01-29 06:22:16,123] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 ny-rides-kelvin:trips_data_all.fhv_external_table is not allowed for this operation because it is currently a EXTERNAL.

(job ID: airflow_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_02_01T00_00_00_00_00_12cc801470e3cb15c8ca42b84054d278)

                                                                                           -----Query Job SQL Follows-----                                                                                            

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.fhv_external_table         PARTITION BY DATE(dropOff_datetime)         CLUSTER BY dispatching_base_num         AS         SELECT * FROM trips_data_all.fhv_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2023-01-29 06:22:16,154] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_fhv_dag, task_id=bq_create_fhv_partitioned_clustered_table_task, execution_date=20190201T000000, start_date=20230129T062212, end_date=20230129T062216
[2023-01-29 06:22:16,169] {standard_task_runner.py:92} ERROR - Failed to execute job 251 for task bq_create_fhv_partitioned_clustered_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 ny-rides-kelvin:trips_data_all.fhv_external_table is not allowed for this operation because it is currently a EXTERNAL.

(job ID: airflow_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_02_01T00_00_00_00_00_12cc801470e3cb15c8ca42b84054d278)

                                                                                           -----Query Job SQL Follows-----                                                                                            

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.fhv_external_table         PARTITION BY DATE(dropOff_datetime)         CLUSTER BY dispatching_base_num         AS         SELECT * FROM trips_data_all.fhv_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2023-01-29 06:22:16,220] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-29 06:22:16,260] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-29 13:29:12,915] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 13:29:12,933] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 13:29:12,934] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 13:29:12,934] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-01-29 13:29:12,935] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 13:29:12,951] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_fhv_partitioned_clustered_table_task> on 2019-02-01 00:00:00+00:00
[2023-01-29 13:29:12,957] {standard_task_runner.py:52} INFO - Started process 2327 to run task
[2023-01-29 13:29:12,964] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'bq_create_fhv_partitioned_clustered_table_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '510', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpuqkqzv3_', '--error-file', '/tmp/tmpuc4wubac']
[2023-01-29 13:29:12,966] {standard_task_runner.py:77} INFO - Job 510: Subtask bq_create_fhv_partitioned_clustered_table_task
[2023-01-29 13:29:13,061] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 13:29:13,128] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=bq_create_fhv_partitioned_clustered_table_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2023-01-29 13:29:13,132] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-01-29 13:29:13,148] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 13:29:13,159] {bigquery.py:1637} INFO - Inserting job ***_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_02_01T00_00_00_00_00_7dfa2306d52b0c4a32bb70fbf40df760
[2023-01-29 13:29:39,094] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_fhv_dag, task_id=bq_create_fhv_partitioned_clustered_table_task, execution_date=20190201T000000, start_date=20230129T132912, end_date=20230129T132939
[2023-01-29 13:29:39,149] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 13:29:39,182] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
