[2023-01-29 06:41:16,116] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 06:41:16,128] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 06:41:16,129] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 06:41:16,130] {taskinstance.py:1239} INFO - Starting attempt 8 of 9
[2023-01-29 06:41:16,130] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 06:41:16,142] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_fhv_partitioned_clustered_table_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 06:41:16,150] {standard_task_runner.py:52} INFO - Started process 1733 to run task
[2023-01-29 06:41:16,154] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'bq_create_fhv_partitioned_clustered_table_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpj1uyjm3t', '--error-file', '/tmp/tmp97jh0fmc']
[2023-01-29 06:41:16,156] {standard_task_runner.py:77} INFO - Job 272: Subtask bq_create_fhv_partitioned_clustered_table_task
[2023-01-29 06:41:16,237] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.bq_create_fhv_partitioned_clustered_table_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 066784a7791c
[2023-01-29 06:41:16,299] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=bq_create_fhv_partitioned_clustered_table_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 06:41:16,301] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-01-29 06:41:16,309] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 06:41:16,317] {bigquery.py:1637} INFO - Inserting job ***_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_01_01T00_00_00_00_00_95ae7b08a881621fe4a8735cf217f1f9
[2023-01-29 06:41:18,094] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.fhv_external_table, error message: Parquet column 'DOlocationID' has type INT64 which does not match the target cpp_type DOUBLE. File: gs://dtc_data_lake_ny-rides-kelvin/raw/fhv_tripdata_2019-06.parquet

(job ID: airflow_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_01_01T00_00_00_00_00_95ae7b08a881621fe4a8735cf217f1f9)

                                                                     -----Query Job SQL Follows-----                                                                     

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.fhv_tripdata          PARTITION BY DATE(dropOff_datetime)         AS         SELECT * FROM trips_data_all.fhv_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2023-01-29 06:41:18,114] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_fhv_dag, task_id=bq_create_fhv_partitioned_clustered_table_task, execution_date=20190101T000000, start_date=20230129T064116, end_date=20230129T064118
[2023-01-29 06:41:18,128] {standard_task_runner.py:92} ERROR - Failed to execute job 272 for task bq_create_fhv_partitioned_clustered_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.fhv_external_table, error message: Parquet column 'DOlocationID' has type INT64 which does not match the target cpp_type DOUBLE. File: gs://dtc_data_lake_ny-rides-kelvin/raw/fhv_tripdata_2019-06.parquet

(job ID: airflow_data_ingestion_fhv_dag_bq_create_fhv_partitioned_clustered_table_task_2019_01_01T00_00_00_00_00_95ae7b08a881621fe4a8735cf217f1f9)

                                                                     -----Query Job SQL Follows-----                                                                     

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE trips_data_all.fhv_tripdata          PARTITION BY DATE(dropOff_datetime)         AS         SELECT * FROM trips_data_all.fhv_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2023-01-29 06:41:18,148] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-29 06:41:18,177] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
