[2023-01-29 10:38:59,290] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.modify_parquet_column_type_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 10:38:59,307] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.modify_parquet_column_type_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2023-01-29 10:38:59,308] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 10:38:59,309] {taskinstance.py:1239} INFO - Starting attempt 9 of 9
[2023-01-29 10:38:59,310] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 10:38:59,322] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): modify_parquet_column_type_task> on 2019-02-01 00:00:00+00:00
[2023-01-29 10:38:59,329] {standard_task_runner.py:52} INFO - Started process 29412 to run task
[2023-01-29 10:38:59,332] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'modify_parquet_column_type_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpj7l4sze7', '--error-file', '/tmp/tmp9nrf1gba']
[2023-01-29 10:38:59,334] {standard_task_runner.py:77} INFO - Job 309: Subtask modify_parquet_column_type_task
[2023-01-29 10:38:59,389] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.modify_parquet_column_type_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 066784a7791c
[2023-01-29 10:38:59,447] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 10:38:59,465] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=modify_parquet_column_type_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2023-01-29 10:38:59,467] {logging_mixin.py:109} INFO - bucket dtc_data_lake_ny-rides-kelvin
[2023-01-29 10:38:59,467] {logging_mixin.py:109} INFO - file_path raw/fhv_tripdata_2019-02.parquet
[2023-01-29 10:38:59,468] {logging_mixin.py:109} INFO - column_name DOlocationID
[2023-01-29 10:38:59,477] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 53, in modify_parquet_column_type
    table = pq.read_table(gcs_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1869, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1697, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 655, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 400, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 376, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: gs://dtc_data_lake_ny-rides-kelvin/raw/fhv_tripdata_2019-02.parquet
[2023-01-29 10:38:59,492] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=modify_parquet_column_type_task, execution_date=20190201T000000, start_date=20230129T103859, end_date=20230129T103859
[2023-01-29 10:38:59,504] {standard_task_runner.py:92} ERROR - Failed to execute job 309 for task modify_parquet_column_type_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 53, in modify_parquet_column_type
    table = pq.read_table(gcs_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1869, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1697, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 655, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 400, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/dataset.py", line 376, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: gs://dtc_data_lake_ny-rides-kelvin/raw/fhv_tripdata_2019-02.parquet
[2023-01-29 10:38:59,547] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-29 10:38:59,581] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
