[2023-01-29 12:15:13,019] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:15:13,030] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:15:13,031] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:15:13,031] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:15:13,032] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:15:13,043] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 12:15:13,048] {standard_task_runner.py:52} INFO - Started process 2553 to run task
[2023-01-29 12:15:13,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9h3y796a', '--error-file', '/tmp/tmp_36qetpe']
[2023-01-29 12:15:13,053] {standard_task_runner.py:77} INFO - Job 356: Subtask cast_parquet_columns_task
[2023-01-29 12:15:13,110] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:15:13,161] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 12:15:13,165] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in cast_parquet_columns
    table = pv.read_csv(dataset_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'fhv_tripdata_{{ execution_date.strftime('%Y-%m') }}.parquet'. Detail: [errno 2] No such file or directory
[2023-01-29 12:15:13,179] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T121513, end_date=20230129T121513
[2023-01-29 12:15:13,191] {standard_task_runner.py:92} ERROR - Failed to execute job 356 for task cast_parquet_columns_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in cast_parquet_columns
    table = pv.read_csv(dataset_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'fhv_tripdata_{{ execution_date.strftime('%Y-%m') }}.parquet'. Detail: [errno 2] No such file or directory
[2023-01-29 12:15:13,226] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-29 12:15:13,260] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:41:40,831] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:41:40,842] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:41:40,843] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:41:40,844] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:41:40,845] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:41:40,857] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 12:41:40,864] {standard_task_runner.py:52} INFO - Started process 6546 to run task
[2023-01-29 12:41:40,867] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4essmw7w', '--error-file', '/tmp/tmpc5lel1pt']
[2023-01-29 12:41:40,869] {standard_task_runner.py:77} INFO - Job 385: Subtask cast_parquet_columns_task
[2023-01-29 12:41:40,926] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:41:40,965] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:41:40,986] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 12:41:40,988] {logging_mixin.py:109} INFO - /opt/***
[2023-01-29 12:41:42,322] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2023-01-29 12:41:42,405] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T124140, end_date=20230129T124142
[2023-01-29 12:41:42,443] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:58:27,516] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:58:27,528] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:58:27,529] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:58:27,530] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:58:27,531] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:58:27,542] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 12:58:27,548] {standard_task_runner.py:52} INFO - Started process 1433 to run task
[2023-01-29 12:58:27,552] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp6s6btfmc', '--error-file', '/tmp/tmpxnjims33']
[2023-01-29 12:58:27,553] {standard_task_runner.py:77} INFO - Job 449: Subtask cast_parquet_columns_task
[2023-01-29 12:58:27,616] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:58:27,664] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:58:27,687] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 12:58:27,689] {logging_mixin.py:109} INFO - /opt/***
[2023-01-29 12:58:32,723] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2023-01-29 12:58:32,771] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T125827, end_date=20230129T125832
[2023-01-29 12:58:32,814] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
