[2023-01-29 12:15:28,004] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:15:28,013] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:15:28,015] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:15:28,015] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-01-29 12:15:28,016] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:15:28,027] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 12:15:28,032] {standard_task_runner.py:52} INFO - Started process 2592 to run task
[2023-01-29 12:15:28,035] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp49adeqs5', '--error-file', '/tmp/tmpwrilxtl1']
[2023-01-29 12:15:28,036] {standard_task_runner.py:77} INFO - Job 357: Subtask cast_parquet_columns_task
[2023-01-29 12:15:28,101] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:15:28,152] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 12:15:28,155] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in cast_parquet_columns
    table = pv.read_csv(dataset_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'fhv_tripdata_{{ execution_date.strftime('%Y-%m') }}.parquet'. Detail: [errno 2] No such file or directory
[2023-01-29 12:15:28,168] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T121528, end_date=20230129T121528
[2023-01-29 12:15:28,180] {standard_task_runner.py:92} ERROR - Failed to execute job 357 for task cast_parquet_columns_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 38, in cast_parquet_columns
    table = pv.read_csv(dataset_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'fhv_tripdata_{{ execution_date.strftime('%Y-%m') }}.parquet'. Detail: [errno 2] No such file or directory
[2023-01-29 12:15:28,210] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-29 12:15:28,252] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:42:36,920] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:42:36,931] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 12:42:36,932] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:42:36,932] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-01-29 12:42:36,933] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:42:36,944] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 12:42:36,950] {standard_task_runner.py:52} INFO - Started process 6743 to run task
[2023-01-29 12:42:36,954] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpa9a_s2s4', '--error-file', '/tmp/tmpk2_3n38l']
[2023-01-29 12:42:36,956] {standard_task_runner.py:77} INFO - Job 391: Subtask cast_parquet_columns_task
[2023-01-29 12:42:37,012] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:42:37,051] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:42:37,070] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 12:42:37,073] {logging_mixin.py:109} INFO - /opt/***
[2023-01-29 12:42:38,458] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2023-01-29 12:42:38,534] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T124236, end_date=20230129T124238
[2023-01-29 12:42:38,576] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-29 13:01:05,230] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 13:01:05,240] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2023-01-29 13:01:05,241] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 13:01:05,242] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2023-01-29 13:01:05,242] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 13:01:05,252] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cast_parquet_columns_task> on 2019-01-01 00:00:00+00:00
[2023-01-29 13:01:05,257] {standard_task_runner.py:52} INFO - Started process 1797 to run task
[2023-01-29 13:01:05,261] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'cast_parquet_columns_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '450', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9unjl300', '--error-file', '/tmp/tmp5kdpclg7']
[2023-01-29 13:01:05,262] {standard_task_runner.py:77} INFO - Job 450: Subtask cast_parquet_columns_task
[2023-01-29 13:01:05,318] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.cast_parquet_columns_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 13:01:05,363] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 13:01:05,383] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=cast_parquet_columns_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2023-01-29 13:01:06,616] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2023-01-29 13:01:06,716] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=cast_parquet_columns_task, execution_date=20190101T000000, start_date=20230129T130105, end_date=20230129T130106
[2023-01-29 13:01:06,836] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
