[2023-01-24 01:46:19,979] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2023-01-24 01:46:19,991] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2023-01-24 01:46:19,991] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 01:46:19,991] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-01-24 01:46:19,991] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 01:46:20,006] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2021-01-02 06:00:00+00:00
[2023-01-24 01:46:20,010] {standard_task_runner.py:52} INFO - Started process 3169 to run task
[2023-01-24 01:46:20,015] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp7iec83mh', '--error-file', '/tmp/tmp2wep1b5j']
[2023-01-24 01:46:20,017] {standard_task_runner.py:77} INFO - Job 55: Subtask wget
[2023-01-24 01:46:20,085] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2021-01-02T06:00:00+00:00 [running]> on host 6018d13d82e3
[2023-01-24 01:46:20,155] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T06:00:00+00:00
[2023-01-24 01:46:20,156] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-24 01:46:20,157] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet -O /opt/***/output.parquet']
[2023-01-24 01:46:20,168] {subprocess.py:85} INFO - Output:
[2023-01-24 01:46:20,171] {subprocess.py:89} INFO - bash: wget: command not found
[2023-01-24 01:46:20,171] {subprocess.py:93} INFO - Command exited with return code 127
[2023-01-24 01:46:20,188] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-24 01:46:20,197] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20210102T060000, start_date=20230124T014619, end_date=20230124T014620
[2023-01-24 01:46:20,214] {standard_task_runner.py:92} ERROR - Failed to execute job 55 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-24 01:46:20,229] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-24 01:46:20,278] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
